version: "3.1"
services: 
  website:
    build: .
    volumes: 
      - ./:/var/www/html/
    ports: 
      - "80:80"
    depends_on: 
      - database

  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root