version: "3.1"
services: 
  website:
    build: .
    volumes: 
      - ./:/var/www/html/
    ports: 
      - "80:80"
    depends_on: 
      - database
      - static

  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    
  static:
    image: nginx:latest
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
      - ./static/:/www/data/static/
    ports:
      - "8080:80"
    command: /bin/bash -c "cat < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"